// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt42XksRw9ZtbAPg1mqd3V4bthimU0mow',
    appId: '1:1064359126878:web:ae0b904340157f628991cf',
    messagingSenderId: '1064359126878',
    projectId: 'chat-app-73e6b',
    authDomain: 'chat-app-73e6b.firebaseapp.com',
    storageBucket: 'chat-app-73e6b.firebasestorage.app',
    measurementId: 'G-T86HKPR0HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARYqAp2BBeJPbB4v0Al0JsntpmX8EVBnA',
    appId: '1:1064359126878:android:8f0093aa766fe1db8991cf',
    messagingSenderId: '1064359126878',
    projectId: 'chat-app-73e6b',
    storageBucket: 'chat-app-73e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLSJJ9z7JiQI39-lZCrBBqmdEFDs6NSM',
    appId: '1:1064359126878:ios:50d76ad676dc02d58991cf',
    messagingSenderId: '1064359126878',
    projectId: 'chat-app-73e6b',
    storageBucket: 'chat-app-73e6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPLSJJ9z7JiQI39-lZCrBBqmdEFDs6NSM',
    appId: '1:1064359126878:ios:50d76ad676dc02d58991cf',
    messagingSenderId: '1064359126878',
    projectId: 'chat-app-73e6b',
    storageBucket: 'chat-app-73e6b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt42XksRw9ZtbAPg1mqd3V4bthimU0mow',
    appId: '1:1064359126878:web:ea4344b94ae795ec8991cf',
    messagingSenderId: '1064359126878',
    projectId: 'chat-app-73e6b',
    authDomain: 'chat-app-73e6b.firebaseapp.com',
    storageBucket: 'chat-app-73e6b.firebasestorage.app',
    measurementId: 'G-279YS3RVXH',
  );
}
